/home/pason/Works/VNS/others/simple-task-manager/frappe-bench/env/lib/python3.13/site-packages/rq/worker.py:1302: DeprecationWarning: This process (pid=21374) is multi-threaded, use of fork() may lead to deadlocks in the child.
  child_pid = os.fork()
/home/pason/Works/VNS/others/simple-task-manager/frappe-bench/env/lib/python3.13/site-packages/rq/worker.py:1302: DeprecationWarning: This process (pid=21374) is multi-threaded, use of fork() may lead to deadlocks in the child.
  child_pid = os.fork()
/home/pason/Works/VNS/others/simple-task-manager/frappe-bench/env/lib/python3.13/site-packages/rq/worker.py:1302: DeprecationWarning: This process (pid=29517) is multi-threaded, use of fork() may lead to deadlocks in the child.
  child_pid = os.fork()
2025-09-26 10:34:23,676 Could not connect to Redis instance: Connection closed by server. Retrying in 1 seconds...
2025-09-26 10:34:23,676 Could not connect to Redis instance: Error 111 connecting to 127.0.0.1:11000. Connection refused. Retrying in 2 seconds...
2025-09-26 10:34:24,676 Could not connect to Redis instance: Error 111 connecting to 127.0.0.1:11000. Connection refused. Retrying in 2 seconds...
2025-09-26 10:34:25,677 Could not connect to Redis instance: Error 111 connecting to 127.0.0.1:11000. Connection refused. Retrying in 2 seconds...
2025-09-26 10:34:26,677 Could not connect to Redis instance: Error 111 connecting to 127.0.0.1:11000. Connection refused. Retrying in 4 seconds...
2025-09-26 10:34:27,678 Could not connect to Redis instance: Error 111 connecting to 127.0.0.1:11000. Connection refused. Retrying in 2 seconds...
2025-09-26 10:34:29,679 Could not connect to Redis instance: Error 111 connecting to 127.0.0.1:11000. Connection refused. Retrying in 2 seconds...
2025-09-26 10:34:30,678 Could not connect to Redis instance: Error 111 connecting to 127.0.0.1:11000. Connection refused. Retrying in 8 seconds...
2025-09-26 10:34:31,680 Could not connect to Redis instance: Error 111 connecting to 127.0.0.1:11000. Connection refused. Retrying in 2 seconds...
2025-09-26 10:34:33,681 Could not connect to Redis instance: Error 111 connecting to 127.0.0.1:11000. Connection refused. Retrying in 2 seconds...
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/pason/Works/VNS/others/simple-task-manager/frappe-bench/env/lib/python3.13/site-packages/redis/connection.py", line 385, in connect_check_health
    sock = self.retry.call_with_retry(
        lambda: self._connect(), lambda error: self.disconnect(error)
    )
  File "/home/pason/Works/VNS/others/simple-task-manager/frappe-bench/env/lib/python3.13/site-packages/redis/retry.py", line 87, in call_with_retry
    return do()
  File "/home/pason/Works/VNS/others/simple-task-manager/frappe-bench/env/lib/python3.13/site-packages/redis/connection.py", line 386, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
            ~~~~~~~~~~~~~^^
  File "/home/pason/Works/VNS/others/simple-task-manager/frappe-bench/env/lib/python3.13/site-packages/redis/connection.py", line 797, in _connect
    raise err
  File "/home/pason/Works/VNS/others/simple-task-manager/frappe-bench/env/lib/python3.13/site-packages/redis/connection.py", line 781, in _connect
    sock.connect(socket_address)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pason/Works/VNS/others/simple-task-manager/frappe-bench/env/lib/python3.13/site-packages/redis/retry.py", line 87, in call_with_retry
    return do()
  File "/home/pason/Works/VNS/others/simple-task-manager/frappe-bench/env/lib/python3.13/site-packages/redis/client.py", line 919, in <lambda>
    lambda: command(*args, **kwargs),
            ~~~~~~~^^^^^^^^^^^^^^^^^
  File "/home/pason/Works/VNS/others/simple-task-manager/frappe-bench/env/lib/python3.13/site-packages/redis/client.py", line 936, in try_read
    if not conn.can_read(timeout=timeout):
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/home/pason/Works/VNS/others/simple-task-manager/frappe-bench/env/lib/python3.13/site-packages/redis/connection.py", line 617, in can_read
    self.connect()
    ~~~~~~~~~~~~^^
  File "/home/pason/Works/VNS/others/simple-task-manager/frappe-bench/env/lib/python3.13/site-packages/redis/connection.py", line 379, in connect
    self.connect_check_health(check_health=True)
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/home/pason/Works/VNS/others/simple-task-manager/frappe-bench/env/lib/python3.13/site-packages/redis/connection.py", line 391, in connect_check_health
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to 127.0.0.1:13000. Connection refused.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pason/Works/VNS/others/simple-task-manager/frappe-bench/env/lib/python3.13/site-packages/redis/connection.py", line 385, in connect_check_health
    sock = self.retry.call_with_retry(
        lambda: self._connect(), lambda error: self.disconnect(error)
    )
  File "/home/pason/Works/VNS/others/simple-task-manager/frappe-bench/env/lib/python3.13/site-packages/redis/retry.py", line 87, in call_with_retry
    return do()
  File "/home/pason/Works/VNS/others/simple-task-manager/frappe-bench/env/lib/python3.13/site-packages/redis/connection.py", line 386, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
            ~~~~~~~~~~~~~^^
  File "/home/pason/Works/VNS/others/simple-task-manager/frappe-bench/env/lib/python3.13/site-packages/redis/connection.py", line 797, in _connect
    raise err
  File "/home/pason/Works/VNS/others/simple-task-manager/frappe-bench/env/lib/python3.13/site-packages/redis/connection.py", line 781, in _connect
    sock.connect(socket_address)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.13/threading.py", line 1043, in _bootstrap_inner
    self.run()
    ~~~~~~~~^^
  File "/home/pason/Works/VNS/others/simple-task-manager/frappe-bench/env/lib/python3.13/site-packages/redis/client.py", line 1273, in run
    self.exception_handler(e, pubsub, self)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/home/pason/Works/VNS/others/simple-task-manager/frappe-bench/env/lib/python3.13/site-packages/redis/client.py", line 1269, in run
    pubsub.get_message(ignore_subscribe_messages=True, timeout=sleep_time)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pason/Works/VNS/others/simple-task-manager/frappe-bench/env/lib/python3.13/site-packages/redis/client.py", line 1131, in get_message
    response = self.parse_response(block=(timeout is None), timeout=timeout)
  File "/home/pason/Works/VNS/others/simple-task-manager/frappe-bench/env/lib/python3.13/site-packages/redis/client.py", line 942, in parse_response
    response = self._execute(conn, try_read)
  File "/home/pason/Works/VNS/others/simple-task-manager/frappe-bench/env/lib/python3.13/site-packages/redis/client.py", line 918, in _execute
    return conn.retry.call_with_retry(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^
        lambda: command(*args, **kwargs),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        lambda _: self._reconnect(conn),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/pason/Works/VNS/others/simple-task-manager/frappe-bench/env/lib/python3.13/site-packages/redis/retry.py", line 90, in call_with_retry
    fail(error)
    ~~~~^^^^^^^
  File "/home/pason/Works/VNS/others/simple-task-manager/frappe-bench/env/lib/python3.13/site-packages/redis/client.py", line 920, in <lambda>
    lambda _: self._reconnect(conn),
              ~~~~~~~~~~~~~~~^^^^^^
  File "/home/pason/Works/VNS/others/simple-task-manager/frappe-bench/env/lib/python3.13/site-packages/redis/client.py", line 908, in _reconnect
    conn.connect()
    ~~~~~~~~~~~~^^
  File "/home/pason/Works/VNS/others/simple-task-manager/frappe-bench/env/lib/python3.13/site-packages/redis/connection.py", line 379, in connect
    self.connect_check_health(check_health=True)
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/home/pason/Works/VNS/others/simple-task-manager/frappe-bench/env/lib/python3.13/site-packages/redis/connection.py", line 391, in connect_check_health
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to 127.0.0.1:13000. Connection refused.
2025-09-26 10:34:35,681 Could not connect to Redis instance: Error 111 connecting to 127.0.0.1:11000. Connection refused. Retrying in 2 seconds...
2025-09-26 10:34:37,682 Could not connect to Redis instance: Error 111 connecting to 127.0.0.1:11000. Connection refused. Retrying in 2 seconds...
2025-09-26 10:34:38,679 Could not connect to Redis instance: Error 111 connecting to 127.0.0.1:11000. Connection refused. Retrying in 16 seconds...
2025-09-26 10:34:39,683 Could not connect to Redis instance: Error 111 connecting to 127.0.0.1:11000. Connection refused. Retrying in 2 seconds...
2025-09-26 10:34:41,684 Could not connect to Redis instance: Error 111 connecting to 127.0.0.1:11000. Connection refused. Retrying in 2 seconds...
2025-09-26 10:34:43,684 Could not connect to Redis instance: Error 111 connecting to 127.0.0.1:11000. Connection refused. Retrying in 2 seconds...
2025-09-26 10:34:45,685 Could not connect to Redis instance: Error 111 connecting to 127.0.0.1:11000. Connection refused. Retrying in 2 seconds...
2025-09-26 10:34:47,686 Could not connect to Redis instance: Error 111 connecting to 127.0.0.1:11000. Connection refused. Retrying in 2 seconds...
2025-09-26 10:34:49,847 Could not connect to Redis instance: Error 111 connecting to 127.0.0.1:11000. Connection refused. Retrying in 2 seconds...
2025-09-26 10:34:51,847 Could not connect to Redis instance: Error 111 connecting to 127.0.0.1:11000. Connection refused. Retrying in 2 seconds...
2025-09-26 10:34:53,848 Could not connect to Redis instance: Error 111 connecting to 127.0.0.1:11000. Connection refused. Retrying in 2 seconds...
2025-09-26 10:34:54,680 Could not connect to Redis instance: Error 111 connecting to 127.0.0.1:11000. Connection refused. Retrying in 32 seconds...
2025-09-26 10:34:55,849 Could not connect to Redis instance: Error 111 connecting to 127.0.0.1:11000. Connection refused. Retrying in 2 seconds...
2025-09-26 10:34:57,850 Could not connect to Redis instance: Error 111 connecting to 127.0.0.1:11000. Connection refused. Retrying in 2 seconds...
2025-09-26 10:34:59,851 Could not connect to Redis instance: Error 111 connecting to 127.0.0.1:11000. Connection refused. Retrying in 2 seconds...
2025-09-26 10:35:01,851 Could not connect to Redis instance: Error 111 connecting to 127.0.0.1:11000. Connection refused. Retrying in 2 seconds...
2025-09-26 10:35:03,852 Could not connect to Redis instance: Error 111 connecting to 127.0.0.1:11000. Connection refused. Retrying in 2 seconds...
2025-09-26 10:35:05,853 Could not connect to Redis instance: Error 111 connecting to 127.0.0.1:11000. Connection refused. Retrying in 2 seconds...
2025-09-26 10:35:07,853 Could not connect to Redis instance: Error 111 connecting to 127.0.0.1:11000. Connection refused. Retrying in 2 seconds...
2025-09-26 10:35:09,854 Could not connect to Redis instance: Error 111 connecting to 127.0.0.1:11000. Connection refused. Retrying in 2 seconds...
2025-09-26 10:35:11,855 Could not connect to Redis instance: Error 111 connecting to 127.0.0.1:11000. Connection refused. Retrying in 2 seconds...
2025-09-26 10:35:13,856 Could not connect to Redis instance: Error 111 connecting to 127.0.0.1:11000. Connection refused. Retrying in 2 seconds...
2025-09-26 10:35:15,856 Could not connect to Redis instance: Error 111 connecting to 127.0.0.1:11000. Connection refused. Retrying in 2 seconds...
2025-09-26 10:35:17,857 Could not connect to Redis instance: Error 111 connecting to 127.0.0.1:11000. Connection refused. Retrying in 2 seconds...
2025-09-26 10:35:19,858 Could not connect to Redis instance: Error 111 connecting to 127.0.0.1:11000. Connection refused. Retrying in 2 seconds...
2025-09-26 10:35:21,858 Could not connect to Redis instance: Error 111 connecting to 127.0.0.1:11000. Connection refused. Retrying in 2 seconds...
2025-09-26 10:35:23,860 Could not connect to Redis instance: Error 111 connecting to 127.0.0.1:11000. Connection refused. Retrying in 2 seconds...
2025-09-26 10:35:25,861 Could not connect to Redis instance: Error 111 connecting to 127.0.0.1:11000. Connection refused. Retrying in 2 seconds...
2025-09-26 10:35:26,681 Could not connect to Redis instance: Error 111 connecting to 127.0.0.1:11000. Connection refused. Retrying in 60 seconds...
2025-09-26 10:35:27,861 Could not connect to Redis instance: Error 111 connecting to 127.0.0.1:11000. Connection refused. Retrying in 2 seconds...
2025-09-26 10:35:29,862 Could not connect to Redis instance: Error 111 connecting to 127.0.0.1:11000. Connection refused. Retrying in 2 seconds...
2025-09-26 10:35:31,863 Could not connect to Redis instance: Error 111 connecting to 127.0.0.1:11000. Connection refused. Retrying in 2 seconds...
2025-09-26 10:35:33,864 Could not connect to Redis instance: Error 111 connecting to 127.0.0.1:11000. Connection refused. Retrying in 2 seconds...
2025-09-26 10:35:35,864 Could not connect to Redis instance: Error 111 connecting to 127.0.0.1:11000. Connection refused. Retrying in 2 seconds...
2025-09-26 10:35:37,865 Could not connect to Redis instance: Error 111 connecting to 127.0.0.1:11000. Connection refused. Retrying in 2 seconds...
2025-09-26 10:35:39,866 Could not connect to Redis instance: Error 111 connecting to 127.0.0.1:11000. Connection refused. Retrying in 2 seconds...
2025-09-26 10:35:41,867 Could not connect to Redis instance: Error 111 connecting to 127.0.0.1:11000. Connection refused. Retrying in 2 seconds...
2025-09-26 10:35:43,868 Could not connect to Redis instance: Error 111 connecting to 127.0.0.1:11000. Connection refused. Retrying in 2 seconds...
2025-09-26 10:35:45,869 Could not connect to Redis instance: Error 111 connecting to 127.0.0.1:11000. Connection refused. Retrying in 2 seconds...
2025-09-26 10:35:47,869 Could not connect to Redis instance: Error 111 connecting to 127.0.0.1:11000. Connection refused. Retrying in 2 seconds...
2025-09-26 10:35:49,870 Could not connect to Redis instance: Error 111 connecting to 127.0.0.1:11000. Connection refused. Retrying in 2 seconds...
2025-09-26 10:35:51,871 Could not connect to Redis instance: Error 111 connecting to 127.0.0.1:11000. Connection refused. Retrying in 2 seconds...
2025-09-26 10:35:53,872 Could not connect to Redis instance: Error 111 connecting to 127.0.0.1:11000. Connection refused. Retrying in 2 seconds...
2025-09-26 10:35:55,873 Could not connect to Redis instance: Error 111 connecting to 127.0.0.1:11000. Connection refused. Retrying in 2 seconds...
2025-09-26 10:35:57,873 Could not connect to Redis instance: Error 111 connecting to 127.0.0.1:11000. Connection refused. Retrying in 2 seconds...
2025-09-26 10:35:59,874 Could not connect to Redis instance: Error 111 connecting to 127.0.0.1:11000. Connection refused. Retrying in 2 seconds...
2025-09-26 10:36:01,875 Could not connect to Redis instance: Error 111 connecting to 127.0.0.1:11000. Connection refused. Retrying in 2 seconds...
2025-09-26 10:36:03,876 Could not connect to Redis instance: Error 111 connecting to 127.0.0.1:11000. Connection refused. Retrying in 2 seconds...
2025-09-26 10:36:05,877 Could not connect to Redis instance: Error 111 connecting to 127.0.0.1:11000. Connection refused. Retrying in 2 seconds...
2025-09-26 10:36:07,877 Could not connect to Redis instance: Error 111 connecting to 127.0.0.1:11000. Connection refused. Retrying in 2 seconds...
2025-09-26 10:36:09,878 Could not connect to Redis instance: Error 111 connecting to 127.0.0.1:11000. Connection refused. Retrying in 2 seconds...
2025-09-26 10:36:11,879 Could not connect to Redis instance: Error 111 connecting to 127.0.0.1:11000. Connection refused. Retrying in 2 seconds...
2025-09-26 10:36:13,879 Could not connect to Redis instance: Error 111 connecting to 127.0.0.1:11000. Connection refused. Retrying in 2 seconds...
2025-09-26 10:36:15,881 Could not connect to Redis instance: Error 111 connecting to 127.0.0.1:11000. Connection refused. Retrying in 2 seconds...
2025-09-26 10:36:17,882 Could not connect to Redis instance: Error 111 connecting to 127.0.0.1:11000. Connection refused. Retrying in 2 seconds...
2025-09-26 10:36:19,883 Could not connect to Redis instance: Error 111 connecting to 127.0.0.1:11000. Connection refused. Retrying in 2 seconds...
2025-09-26 10:36:21,884 Could not connect to Redis instance: Error 111 connecting to 127.0.0.1:11000. Connection refused. Retrying in 2 seconds...
2025-09-26 10:36:23,884 Could not connect to Redis instance: Error 111 connecting to 127.0.0.1:11000. Connection refused. Retrying in 2 seconds...
2025-09-26 10:36:25,885 Could not connect to Redis instance: Error 111 connecting to 127.0.0.1:11000. Connection refused. Retrying in 2 seconds...
2025-09-26 10:36:26,681 Could not connect to Redis instance: Error 111 connecting to 127.0.0.1:11000. Connection refused. Retrying in 60 seconds...
2025-09-26 10:36:27,886 Could not connect to Redis instance: Error 111 connecting to 127.0.0.1:11000. Connection refused. Retrying in 2 seconds...
2025-09-26 10:36:29,887 Could not connect to Redis instance: Error 111 connecting to 127.0.0.1:11000. Connection refused. Retrying in 2 seconds...
2025-09-26 10:36:31,888 Could not connect to Redis instance: Error 111 connecting to 127.0.0.1:11000. Connection refused. Retrying in 2 seconds...
2025-09-26 10:36:33,888 Could not connect to Redis instance: Error 111 connecting to 127.0.0.1:11000. Connection refused. Retrying in 2 seconds...
2025-09-26 10:36:35,889 Could not connect to Redis instance: Error 111 connecting to 127.0.0.1:11000. Connection refused. Retrying in 2 seconds...
2025-09-26 10:36:37,890 Could not connect to Redis instance: Error 111 connecting to 127.0.0.1:11000. Connection refused. Retrying in 2 seconds...
2025-09-26 10:36:39,891 Could not connect to Redis instance: Error 111 connecting to 127.0.0.1:11000. Connection refused. Retrying in 2 seconds...
2025-09-26 10:36:41,891 Could not connect to Redis instance: Error 111 connecting to 127.0.0.1:11000. Connection refused. Retrying in 2 seconds...
2025-09-26 10:36:43,892 Could not connect to Redis instance: Error 111 connecting to 127.0.0.1:11000. Connection refused. Retrying in 2 seconds...
2025-09-26 10:36:45,892 Could not connect to Redis instance: Error 111 connecting to 127.0.0.1:11000. Connection refused. Retrying in 2 seconds...
2025-09-26 10:36:47,893 Could not connect to Redis instance: Error 111 connecting to 127.0.0.1:11000. Connection refused. Retrying in 2 seconds...
2025-09-26 10:36:49,894 Could not connect to Redis instance: Error 111 connecting to 127.0.0.1:11000. Connection refused. Retrying in 2 seconds...
2025-09-26 10:36:51,894 Could not connect to Redis instance: Error 111 connecting to 127.0.0.1:11000. Connection refused. Retrying in 2 seconds...
2025-09-26 10:36:53,895 Could not connect to Redis instance: Error 111 connecting to 127.0.0.1:11000. Connection refused. Retrying in 2 seconds...
2025-09-26 10:36:55,896 Could not connect to Redis instance: Error 111 connecting to 127.0.0.1:11000. Connection refused. Retrying in 2 seconds...
2025-09-26 10:36:57,897 Could not connect to Redis instance: Error 111 connecting to 127.0.0.1:11000. Connection refused. Retrying in 2 seconds...
2025-09-26 10:36:59,898 Could not connect to Redis instance: Error 111 connecting to 127.0.0.1:11000. Connection refused. Retrying in 2 seconds...
2025-09-26 10:37:01,898 Could not connect to Redis instance: Error 111 connecting to 127.0.0.1:11000. Connection refused. Retrying in 2 seconds...
2025-09-26 10:37:03,899 Could not connect to Redis instance: Error 111 connecting to 127.0.0.1:11000. Connection refused. Retrying in 2 seconds...
2025-09-26 10:37:05,900 Could not connect to Redis instance: Error 111 connecting to 127.0.0.1:11000. Connection refused. Retrying in 2 seconds...
2025-09-26 10:37:07,900 Could not connect to Redis instance: Error 111 connecting to 127.0.0.1:11000. Connection refused. Retrying in 2 seconds...
2025-09-26 10:37:09,901 Could not connect to Redis instance: Error 111 connecting to 127.0.0.1:11000. Connection refused. Retrying in 2 seconds...
2025-09-26 10:37:11,902 Could not connect to Redis instance: Error 111 connecting to 127.0.0.1:11000. Connection refused. Retrying in 2 seconds...
2025-09-26 10:37:13,903 Could not connect to Redis instance: Error 111 connecting to 127.0.0.1:11000. Connection refused. Retrying in 2 seconds...
2025-09-26 10:37:15,903 Could not connect to Redis instance: Error 111 connecting to 127.0.0.1:11000. Connection refused. Retrying in 2 seconds...
2025-09-26 10:37:17,905 Could not connect to Redis instance: Error 111 connecting to 127.0.0.1:11000. Connection refused. Retrying in 2 seconds...
2025-09-26 10:37:19,906 Could not connect to Redis instance: Error 111 connecting to 127.0.0.1:11000. Connection refused. Retrying in 2 seconds...
2025-09-26 10:37:21,907 Could not connect to Redis instance: Error 111 connecting to 127.0.0.1:11000. Connection refused. Retrying in 2 seconds...
2025-09-26 10:37:23,907 Could not connect to Redis instance: Error 111 connecting to 127.0.0.1:11000. Connection refused. Retrying in 2 seconds...
2025-09-26 10:37:25,908 Could not connect to Redis instance: Error 111 connecting to 127.0.0.1:11000. Connection refused. Retrying in 2 seconds...
2025-09-26 10:37:26,682 Could not connect to Redis instance: Error 111 connecting to 127.0.0.1:11000. Connection refused. Retrying in 60 seconds...
2025-09-26 10:37:27,909 Could not connect to Redis instance: Error 111 connecting to 127.0.0.1:11000. Connection refused. Retrying in 2 seconds...
2025-09-26 10:37:29,910 Could not connect to Redis instance: Error 111 connecting to 127.0.0.1:11000. Connection refused. Retrying in 2 seconds...
2025-09-26 10:37:31,911 Could not connect to Redis instance: Error 111 connecting to 127.0.0.1:11000. Connection refused. Retrying in 2 seconds...
2025-09-26 10:37:33,911 Could not connect to Redis instance: Error 111 connecting to 127.0.0.1:11000. Connection refused. Retrying in 2 seconds...
2025-09-26 10:37:35,912 Could not connect to Redis instance: Error 111 connecting to 127.0.0.1:11000. Connection refused. Retrying in 2 seconds...
2025-09-26 10:37:37,913 Could not connect to Redis instance: Error 111 connecting to 127.0.0.1:11000. Connection refused. Retrying in 2 seconds...
2025-09-26 10:37:39,913 Could not connect to Redis instance: Error 111 connecting to 127.0.0.1:11000. Connection refused. Retrying in 2 seconds...
2025-09-26 10:37:42,712 Could not connect to Redis instance: Error 111 connecting to 127.0.0.1:11000. Connection refused. Retrying in 2 seconds...
2025-09-26 10:37:44,713 Could not connect to Redis instance: Error 111 connecting to 127.0.0.1:11000. Connection refused. Retrying in 2 seconds...
2025-09-26 10:37:46,714 Could not connect to Redis instance: Error 111 connecting to 127.0.0.1:11000. Connection refused. Retrying in 2 seconds...
2025-09-26 10:37:48,715 Could not connect to Redis instance: Error 111 connecting to 127.0.0.1:11000. Connection refused. Retrying in 2 seconds...
2025-09-26 10:37:50,716 Could not connect to Redis instance: Error 111 connecting to 127.0.0.1:11000. Connection refused. Retrying in 2 seconds...
2025-09-26 10:37:52,717 Could not connect to Redis instance: Error 111 connecting to 127.0.0.1:11000. Connection refused. Retrying in 2 seconds...
2025-09-26 10:37:54,717 Could not connect to Redis instance: Error 111 connecting to 127.0.0.1:11000. Connection refused. Retrying in 2 seconds...
/home/pason/Works/VNS/others/simple-task-manager/frappe-bench/env/lib/python3.13/site-packages/rq/worker.py:1302: DeprecationWarning: This process (pid=53949) is multi-threaded, use of fork() may lead to deadlocks in the child.
  child_pid = os.fork()
/home/pason/Works/VNS/others/simple-task-manager/frappe-bench/env/lib/python3.13/site-packages/rq/worker.py:1302: DeprecationWarning: This process (pid=158140) is multi-threaded, use of fork() may lead to deadlocks in the child.
  child_pid = os.fork()
